### ISSUE TITLE
The design of the nautilus-webui.

### ISSUE THREAD

**Issue by FledgeXu** [openzim/nautilus-webui#13]
The purpose of this issue is to track the discussions about the design of webui.

Figma link:
https://www.figma.com/file/CoOmezy65NtNKSCtyC9jB0/nautilus-webui?type=design&node-id=0%3A1&t=kV6lVzqL2yySdrlY-1

**Comment by rgaudin** [comment]
Nice ; I didn't think we'd collect the user's name but I think it brings clarity. Here are my comments.

- We definitely don't want to welcome new users by asking for their name.  I think there are two scenarios: new and returning users. For returning users, `3` is fine. For new users, the same but without the side bar and with a “Start now”-like button.
- `2` is great to go from that welcome page to `3`. Wording describing usage and encouraging nickname would be better. We may want to collect one's email address (to send a notification with download link). This might be the place to get it.
- I like “Collection”. Way better than _Session_ 😅
- “ZIM” is always spelled in all caps. I see you copied strings from youzim.it and I don't understand how @kelson42 let that happen 😉
- I think the expiration date (or time remaining) is a very important information that should be reflected because it's gonna be set initially to 7d (from first file upload) and once this expires, neither the source file nor the ZIM files will be available.
- I imagine the ZIM metadata would be behind “Extra settings”. Just to be clear, we won't pre-populate those so filling them will be mandatory. `Title` might be taken from Collection name, `Language` will default to English but we want people to set the `Description` and the Illustration. @Popolechien @kelson42 or don't we? Given this is not meant to enter Kiwix Library, we could have a default Nautilus illustration and Description… `Name` would be prepopulated and changeable.
- I imagine the cog icons lead to metadata customization. Would that trigger a _bulk_ one if you selected multiple files? Would deletion be handled inside that _per-file settings_?
- “Downloaded files” doesn't make much sense. “Created ZIM files” would be more explicit
- I love the shell 👏

@Popolechien @kelson42 please share your thoughts.

**Comment by Popolechien** [comment]
I am not sure I get the point of asking people for their names. Are we creating accounts? Do we _want_ to create accounts? What are the odds of someone returning to ask for a previously generated zim file?

**Comment by rgaudin** [comment]
Well maybe read the https://github.com/openzim/nautilus-webui/blob/main/SOW.md first (but that's based on our discussion).

In short:
- We don't want to handle Accounts (for now, maybe in a distant future to handle above-limit requests)
- We identify returning users specifically because we don't have accounts and we want to encourage users to _just drop files and get a ZIM_
- Because it'd be so easy to upload files, we want to reduce the number of files uploaded but never followed upon (because we pay for each of them!)
- So we want to show returning users what they started so they get a chance to continue/edit/remove

Not asking for “a name” might bring a lot of confusion as users might not now how the website is tracking them (a simple cookie). By setting a name (we can autofill we something like “John Doe 3789” or something funnier), we ake it clear that the user is identified. The “Log-out” icon makes it clear as well that the user can remove this identification (again, just a cookie). We could trigger a warning on that logout and/or delete any not-requested collection for instance (as there is no coming back from logout)

Makes sense?

**Comment by Popolechien** [comment]
> Because it'd be so easy to upload files, we want to reduce the number of files uploaded but never followed upon (because we pay for each of them!)

With an upper limite at 100MiB the savings would be marginal, wouldn't they? If there's any savings to be made I would discard the email function (not saying we should but I'm looking at numbers and that's where I see money).

> So we want to show returning users what they started so they get a chance to continue/edit/remove

I would simply list the actual zim files rather than the source files. If we have say 100+ files that had been previously uploaded the display would be cumbersome and put the onus on us to make it visually digestible.

On a side note, for the cookie part we should make sure that it uses (or takes into account) [Chrome's privacy sandbox](https://www.adexchanger.com/privacy/the-chrome-privacy-sandbox-apis-will-be-generally-available-for-all-users-in-july/) that will be rolling out in July

**Comment by rgaudin** [comment]
> > Because it'd be so easy to upload files, we want to reduce the number of files uploaded but never followed upon (because we pay for each of them!)
> 
> With an upper limite at 100MiB the savings would be marginal, wouldn't they?

This is a pre-development limit we chose but we have no idea how that will evolve and certainly don't want to re-design the tool to change the limit. The constant being: every bytes we upload, we pay for.

> If there's any savings to be made I would discard the email function (not saying we should but I'm looking at numbers and that's where I see money).

Care to explain? Are we paying to send email? Did we go over the free tier in mailgun? When? Why wasn't this shared?

> > So we want to show returning users what they started so they get a chance to continue/edit/remove
> 
> I would simply list the actual zim files rather than the source files. If we have say 100+ files that had been previously uploaded the display would be cumbersome and put the onus on us to make it visually digestible.

I disagree (I think). Most of the time, there will be no ZIM file to download because that's the end of the process. 
Creating a ZIM files out of your own, curated files is really the core of the tool. Not listing those files would be terrible ; especially with this week-long window to upload and update scheme that we've set up.
It's also very important to list the files so the user sees how they are named (automatically, from filename) and incitate him to change the metadata.
Or are you suggesting to move it elsewhere?

> On a side note, for the cookie part we should make sure that it uses (or takes into account) [Chrome's privacy sandbox](https://www.adexchanger.com/privacy/the-chrome-privacy-sandbox-apis-will-be-generally-available-for-all-users-in-july/) that will be rolling out in July

This only concerns _third-parties_ cookies.

**Comment by rgaudin** [comment]
>     * I also do not think that we should ask users for their name first hand. As a matter of fact, we should not ask for names at all: thinking about what to answer (for instance if people want anonymity; or simply asking oneself the question "is this really anonymous") causes friction. I'd suggest going the Google doc (and others)'s way, e.g. assigning users with `random adjective`+`random animal/object` (e.g. _happy narwal_, _bombastic fork_, etc.)

Good ; we're on the same page. Should it be editable though?

>     * I like the idea of copying the zimit look and feel (and I like the shell!) But _Just collection it_ has to be rephrased

As well.

>     * I think `3` should be the default landing. Starting with `2`, one has to look for the `New collection` button, then move to another screen: this again creates friction;

Do you mean `3` or `4`? It's not clear if you account for the rest of the comment.
 
>     * If we list past collections on the left hand side, then we probably don't need to re-list them on top of the page. I would limit this piece of real estate to zim creation (ie the upload box)

It's not. You misunderstood this. Those are ZIM files created with this Collection.

> I think I'm coming around on the idea of listing previously uploaded files. As you mention, people could create a quick zim (without caring about metadata) and then realize that they _do care_ about having correct names, logos, etc.

👍 

> re: mailgun amounts were minimal because whenever we'd beat the threshold it wouldn't be by much. But once we entered paid tier, it did have a non-negligible unit cost.

OK, new information to me. I think email could be really beneficial to retain “Just curious” users that forgot the service after trying it. I have no strong opinion. I suggest we build the feature and maybe we'll turn it off for cost reason or use a different provider.

**Comment by Popolechien** [comment]
@rgaudin I got mixed up with numbers - there's is no `1`. I meant `4` should be the default landing.

Re: collections (on the left-hand side) - we could use it as a link to both edit the collection and/or download the corresponding zim file: there's already a trash icon, we can add a pen and a download arrow. Clicking on the pen would bring back the config page where one can edit the metadata.

**Comment by rgaudin** [comment]
> @rgaudin I got mixed up with numbers - there's is no `1`. I meant `4` should be the default landing.

As I wrote above, there are two scenarios:

- Returning user: then yeah, you arrive right in your last Collection.
- First time user: I think it's a whole different deal because there are a number of messages you need to convey in order to convince user to try the service and generally gain trust. I find it unlikely that a random user starts uploading its file without having a minimum understanding of what will happen.

That's why I think something similar to `3` but without the sidebar (obviously) makes a lot of sense: you have room for basic information ; the FAQ is either visible or reachable (where are files uploaded? For how long, etc) and you get a big action button like “Start Now” that takes you to `4`.

I understand that the least number of actions required the better but I'm afraid mixing those important information and a _Drop files area_ will lead to poor UX: we have to switch the screen anyway. I think one click is bearable.

Looked at https://wetransfer.com/ and realized that you can't drop files directly anymore. Beside the cookie warning that we don't need, you have to accept some terms. You may want to look into the legal aspect of this…

> Re: collections (on the left-hand side) - we could use it as a link to both edit the collection and/or download the corresponding zim file: there's already a trash icon, we can add a pen and a download arrow. Clicking on the pen would bring back the config page where one can edit the metadata.

I don't think I get the rationale behind it: it's a list, in a sidebar. If we have a title and 3 icons it's gonna be cluttered. Icons here should be for repeated actions. Clicking on title would mean _Edit_: no need to restrict this obvious action to an icon while we have the whole Title space available.

Download and Delete, I don't think I see value in them being shortcut there. There's no rush and delete you'd want to request confirmation so better be on the collection page anyway.

**Comment by FledgeXu** [comment]
> That's why I think something similar to 3 but without the sidebar (obviously) makes a lot of sense: you have room for basic information ; the FAQ is either visible or reachable (where are files uploaded? For how long, etc) and you get a big action button like “Start Now” that takes you to 4.

I love this this idea. New user start from a page like ZimInit (without sidebar) and when next time when they use this service they will get the page with sidebar.

Additional information:

About sidebar part, I copy the design from the [ChatGPT](https://chat.openai.com/), so if you want some feeling about this design you can try it own.

And I change the name of pages, Hopefully this will make for a smoother discussion

**Comment by rgaudin** [comment]
After discussing this with @kelson42 and @Popolechien, we've agreed we'd implement the UI based on agreed-upon mockups. We recognize this means a longer and more intensive design process but we're in no rush and when we'll eventually settle, implementation can progress uninterrupted.

@FledgeXu: can you please update the mockup based on the current status of the discussion? Extend it as can be.

All: comments on the mockup are paused here until the new version is shared.

**Comment by Popolechien** [comment]
@siemsie Can you have a look and share your feedback with me directly when you get the chance?

**Comment by Popolechien** [comment]
@FledgeXu Thanks. I made a couple of comments but seeing how many stakeholders we have on it don't act on them until we get several voices and consensus on what to do.

**Comment by FledgeXu** [comment]
@Popolechien I saw you mention in your comment that we need to modify the metadata of individual files, can you think of a more detailed explanation of this piece for me? I'm a bit confused.

**Comment by Popolechien** [comment]
@FledgeXu Not sure _Metadata_ is the right term here but basically here what may need to be documented by the user (case in point: [this particular zim file](https://library.kiwix.org/?lang=eng&q=medical+library))
![Présentation sans titre](https://github.com/openzim/nautilus-webui/assets/21675885/5b6a228c-7a6c-4778-ad1b-8267ed988639)
A, B and C are for the whole zim file (Image, zim description and zim title)
1, 2, 3 (and then 4,5,6 etc.) are each file's title, author and description. If they are not documented then we need to give a chance to the user to do it

**Comment by rgaudin** [comment]
@FledgeXu you are already familiar with the ZIM metadata.
In nautilus, every entry is defined by a `title` and optionally a `description` and an `authors`.
Check https://drive.farm.openzim.org/zimgit-post-disaster_en/ for this particular ZIM ; entries metadata are in `collection.json`.

Nautilus params for this ZIM can be found at https://farm.openzim.org/recipes/zimgit-post-disaster_en/config

**Comment by rgaudin** [comment]
I've looked at the updated mockup ; thank you! I've added a number of comments there.

One additional comment is to maybe use duplicates instead of modifying the same mockup.

As pointed by @Popolechien we lack the ability to set per-file metadata which is important.

**Comment by FledgeXu** [comment]
I just updated the mockup.
https://www.figma.com/file/iBZ8Kw1lOFYzopxp1fLZXB/nautilus-webui-v1?type=design&node-id=0%3A1&t=y97HLzWbA0nWcwrx-1

**Comment by rgaudin** [comment]
Great ; I don't have anything to add at this stage 👍 

I know @kelson42 will take a look at it tomorrow.

**Comment by rgaudin** [comment]
Here's a recap of @kelson42's comments along with some new takes from [Christina's mockup](https://docs.google.com/presentation/d/1FG4RQsyGMIgVng5JrjsLB4AmvQJ3b6xzAG7V7rCm-dk/edit?usp=sharing)

- Drop the User logout feature altogether: we'll store the cookie and that's it. No auto-name, no logout. I failed to convince others that it would have been better 
- There's a single expiration date on the collection. The ZIM themselves expire along so no independent expiration on ZIM files.
- Remove the number next to “Previous collections”: `6/10`. I think it's to show the limit on the number of parallel collections. If a limit is defined and is reached, we'd just disable the “New collection” button with a message.
- The “Previous collections” label doesn't seem much useful and the “New collection” button is prominent (while it should be rarely used: only to create an additional collection). ➡️ A “Collections” label with an icon-based (➕) icon to create a new one instead.
- Created ZIM files box is too bulking and prominent as well. In most cases, user would want to download the latest available one and know that one's in the oven (or not). We could bring more details with a click though.
- A _Preview_ ZIM _card_ as visible on [library.kiwix.org](https://library.kiwix.org/) is a great way to show and edit ZIM Metadata. Edition cursor/icons would lead the way. We'd add Creator/Publisher to our _fake card_ as those are not visible in Kiwix Library.
- Files to upload is the centerpiece of the tool and should feel that way
  - Maybe use more space (wide)
  - Status can be icon-based (OK, uploading, Rejected: too large)
  - Upload datetime would be nice to have maybe on hover of something)
  - Thumbnails for some filetypes is a great idea. Would require extracting them and storing them in the DB (we can open a ticket for that).
  - Selectable Icon/List view and this general OS feel brings a _simplicity_ feel that is welcome
  - Sortable table view is great (Name, Size, Filetype – represented by icon only)
  - File metadata edition should be simplified: Ideally directly in the table (ala Excel) but this might not be practical.

I think uploading files and editing their metadata respond to two different phases of the creation workflow. For this reason I thus propose a _Metadata Edition_ toggle button that expands the files table with the fields to set the metadata.

In the default, _Upload mode_, all entries shows whether they have associated metadata (using icons) and one can hover this area to get a floating card showing the entry's metadata.
Each entry also have an edit icon that toggles the edition mode for that entry only.

Here's a terrible attempt at trying to display what I described above
<img width="1110" alt="Screenshot 2023-06-08 at 07 58 00" src="https://github.com/openzim/nautilus-webui/assets/57929/0ffecbb3-60e7-4eba-9a68-ddfbf1298588">



Note: do we want to limit the number of parallel collections? I think the idea would be to prevent excessive disk usage (which create a bottleneck) but… it could be easily circumvented by using Private browsing windows or different browsers (for those willingly wanting to create more collections).

**Comment by rgaudin** [comment]
> > A Preview ZIM card as visible on [library.kiwix.org](https://library.kiwix.org/) is a great way to show and edit ZIM Metadata. Edition cursor/icons would lead the way. We'd add Creator/Publisher to our fake card as those are not visible in Kiwix Library.
> 
> Could you elaborate on this? Does it mean that we show a preview card for users first and add an "Edit" like button on this card? if users want to edit the config/metadata of this zim file, they need to click the "Edit" like button and edit the config/metadata of the zim file in a modal view?

Yes but I wasn't imagining a modal but the parts of the card themselves can turn into fields. A _Save_ button would flip it back to the preview mode with the new values.

**Comment by rgaudin** [comment]
Thank you! I've added comments on Figma. We're really getting there!!

> The reason I support adding a limit to the number of collections is that we support user-initiated deletion of collections, and adding a limit allows users to delete collections they don't need instead of letting them expire automatically. This way we can save our disk space. However, we can set the limit on the number of collections to be larger so that users don't feel overly restricted.

I have no strong opinion on this. I think that having a limit (and showing it) indeed conveys the information that this service requires resources and someone's paying for it.

**Comment by FledgeXu** [comment]
I just update it.
https://www.figma.com/file/iRBj5DIyMBJ5qyKvKzzxet/nautilus-webui-v3?type=design&node-id=0%3A1&t=vak4Ulu5By1nQ5Ec-1

**Comment by rgaudin** [comment]
Thank you @FledgeXu it's great. We looked at it with @kelson42 on Saturday. I've added a couple comments on the mockup about some missing stuff but beside this I think we're good to go.

**Comment by FledgeXu** [comment]
@Popolechien Yeah, you are not on right document. 
Here is the latest on the V4. 
https://www.figma.com/file/RBjpsnxsdzlXHOsxJUiSB2/nautilus-webui-v4?type=design&node-id=0%3A1&t=02S8VwRBmFTHcxzH-1

> Are both Author and Publisher fields really needed? Feel like duplicates, somewhat confusing. Kiwix-server only shows the "Publisher" field

I kind of feel the same way, I think we can maybe make the publisher default to nautilus?

> language should be some sort of dropdown or autocomplete, else we'll end up with spelling mistakes and therefore "unknown" languages in the library.

Already fixed

> Those need to move to the side callout and ultimately to a distinct page.
Those pages should be a part of kiwix.org?

> Why this "start now" rather than immediately offering a drop box? Adding steps increases user attrition.

I have no strong opinion about it. But I think we should keep it, because there is a lot of customization required, it is better for the user to jump once. The other thing is that we need to delete unused files regularly, which is easier to manage after the jump.

**Comment by Popolechien** [comment]
Yeah I saw that I got on v2, let me move these comments onto v4

**Comment by FledgeXu** [comment]
> I also can't think of a website that I regularly use that doesn't offer the drop box immediately. As indicated, what is the added value of the Startbutton?

In fact, users only need to see this screen after the first login. But you're right, maybe we can remove this interface altogether and just keep the part about creating zim files. But we still need a page to tell the user what the purpose of the site is.

**Comment by Popolechien** [comment]
> But we still need a page to tell the user what the purpose of the site is.

I do not think that `Start Now!` conveys a lot of useful information about the purpose of the page (as opposite to `Drop your files here`).
Users will not come out of nowhere, they will likely have been directed to this page (also, there's the FAQ in case there's any doubt). Anyone attempting to create a zim file is likely to have a basic understanding of what Kiwix does (I think)

**Comment by rgaudin** [comment]
OK, Here are a few comments from discussing v4 with @Popolechien:

- [ ] _Collection Page_ disappears. If one has an existing collection, he arrives on the last one. If not, he gets the _Front Page_
- [ ] _Front Page_: replace the _Start now_ button with a files-welcoming box. It is understood that dragging file(s) here would immediately trigger a UI change to the _Making collection Page_.
- [ ] [Created ZIM files] block: this should be replaced by a download button, either:
  - `[Download My-Music.zim (132MB)] created on Mon Aug 19 07:06`
  - `[[Download My-Music.zim (128MB of files)]] requested on Mon Aug 19 08:45`  <-- button is disabled here as ZIM not ready.
  - This button represents the latest Archive.
  - If there are previous Archives, a `View previous ZIM files` link is displayed that toggles the display of all of them.
- [ ] Metadata edition **must** allow editing the _Name_ of the file and its Filename (despite both having default values)
- [ ] File icon and File Type both represent the same information. We should have a single column for it (so we can sort). Icon can be displayed and Textual file type shown on hover.
- [ ] ZIM metadata Publisher is a single text string
- [ ] ZIM metadata Creator (not author) is a single text string

@FledgeXu if you could update the mockup with those points (tick them here as well), then I'll close this ticket and this will be the base for the first version.

**Comment by FledgeXu** [comment]
Ok, I will update it later.

**Comment by FledgeXu** [comment]
Update: https://www.figma.com/file/BbaN98OoJjZL3BEf1K8DGw/nautilus-webui-v5?type=design&node-id=0%3A1&t=o2bCOUfAWO00otKC-1
> File icon and File Type both represent the same information. We should have a single column for it (so we can sort). Icon can be displayed and Textual file type shown on hover.

I think we should keep text prompts instead of icons, sorting text prompts is more intuitive and this is the default implementation of the file manager in the OS.
<img width="322" alt="image" src="https://github.com/openzim/nautilus-webui/assets/16664654/f793c8fc-0475-4326-a918-3ec036c5b76c">

**Comment by rgaudin** [comment]
Ok ; we may implement an icon view at some point where icons would make sense

**Comment by rgaudin** [comment]
Ok, thank you all for your help, [mockup v5](https://www.figma.com/file/BbaN98OoJjZL3BEf1K8DGw/nautilus-webui-v5?type=design&node-id=0-1&t=jUM33edOGeNuF0qt-0) is the one we'll follow for the first iteration.
