### ISSUE TITLE
The Design of Database.

### ISSUE THREAD

**Issue by FledgeXu** [openzim/nautilus-webui#15]
The purpose of this issue is to track the discussions about the design of Database.

Notice:
All binary files will not be stored in the database, but in the file system. The files will be saved as hash values to save space.

### Table name: users
| id| name|created_date|
|---|---|---|
|int|str|datetime|

### Table name: collections
|id|user_id|name|
|---|---|---|
|int|int(one-to-many)|str|

### Table name: emails
| id | collection_id | email | need_notify | can_promotion |
| --- | --- | ---| --- | ---|
| int | int (many-to-many) | str | bool | bool|

### Table name: files
| id | collection_id | name | description | author |  hash | path | type |
| --- | --- | ---| --- | --- | --- | --- | --- | 
| int | int (many-to-many)| str | str| str| str| str| str|

### Table name: metadata(follows by nautilus's [tags](https://github.com/openzim/nautilus/blob/main/nautiluszim/entrypoint.py))
| id | collection_id| pagination | random | show_description | language | local | tags | title | description | long_description | creator | publisher | favicon | main_logo | secondary_logo | main_color | secondary_color | about_file |
| --- | ---| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| int | int(one-to-one) | int | bool | bool | str | str | str | str | str | str | str | str | str(path) | str(path) | str(path) | str | str | str(path) |

### Table name: archives
| id | collection_id | name | created_date | download_link |
| --- | ---  | ---  | ---  | ---  |
| int | int(one-to-many) | str | datetime | str |

**Comment by rgaudin** [comment]
## Users

- We'd probably go with UUIDs as we'd want them unique and simple.

## Collections

- UUID as well
- We need to record expiration date
- Email should be a property of the collection. It's entered in the context of a collection and the notification should apply to it.

The _spam_ consent is different and I wonder if we shouldn't get rid of it completely. GDPR mandates that this should be user-modifiable at all time. I think it's not worth the trouble.

## Files

- `path` is the S3 bucket key.
- ℹ️ `name` is inited from the original filename. We don't need it anymore then.

Just a reminder that we'll want the paths to be _secrets_ (public but no known/guessable).

## archives

- Metadata are part of archives because it's setings attached to a _request_. On can change those settings are re-request an archive.
- We need a `requested_date`
- We need a `path` as well to record where we'll upload the `collection.json` for that session.
- `download_link` should probably be a download_path as well that is turned into a URL from the Bucket config.

**Comment by rgaudin** [comment]
- It'd be UUIDs everywhere
- I guess the `need_notify` is superfluous. We'd only record email if one wants to be notified.
- As discussed `download_path` in Archive would be `download_url` (as returned by zimfarm)
- `path` in Archive can be called `collection.json_path`. More explicit
- I don't understand the Workers table. The request we'll make to ZF is the _Archive_. It's just not requested until we click the ZIM button and not ready until the ZF calls back.
- Archive thus needs the `status` as well as a `zimfarm_task_id:str` (not strictly required but I think it can be useful)

We need to discuss how we want to handle the file-based metadata: Illustration (favicon), Main-Logo, Secondary-Logo and About file.
I think a practical way would be for it to be a linked to uploaded files in the collection: a select box (or blank).
This would add a new constraint: those files would most likely be ZIM assets and not content and should thus be tagged as such with maybe a tick box (bool) to _hide_ them (ie. not include them in the collection.json) but still upload them to S3

**Comment by rgaudin** [comment]
Good, please use `created_on` and similar pattern for names as it's clearer and works with the fact we'll use datetimes and not dates.

On second thought, Files do need to keep a filename because those will be stored at some in the ZIM and downloadable (from the ZIM). And we can't use our S3 name (that would be meaningless anyway). Would be initialized with the original filename obviously.

I understand Metadata works like this: before initial request, you create one instance of Metadata and update it until you make a request at which point you create a new instance with duplicated values. That new instance gets updated should there be changes and the same process applies in every request.

First, I think the name `Metadata` is not appropriate. I think `Config` is closer to reality. Those are the nautilus CLI params and those are used in part to specify the ZIM metadata.

I can't help but think this is too complex. We don't really care about the config. It's not data we manage. We just want to collect them and transfer them to the ZF. We won't filter based on any of those information for instance.
What about putting it all in a JSON field as a dict (on Archive then). The only transformation we'll do is to transform the favicon/logos/about into URLs.

**Comment by rgaudin** [comment]
- Files still lacks the `filename` and `title` (or `name`)
- `metadata_id` is still present on archives. Shouldn't.
- Did we loose the `created_on` and `expire_on` on collection?

**Comment by rgaudin** [comment]
OK then let's add them back.

For consistency with nautilus, let's use `authors` (plural) and then I think we'll be good for now.

**Comment by rgaudin** [comment]
> Do we need to add `expire_on` to `archives`?

No, we'll set the file expiration date on S3 using the collection's expiration date. We have no reason to and I think keeping a single expiration date is better in terms of UX.

**Comment by rgaudin** [comment]
LGTM 👍
