### ISSUE TITLE
Remove `pymongo` from depedencies.

### ISSUE THREAD

**Issue by FledgeXu** [openzim/nautilus-webui#28]
`nautilus-webui` used some code from the `zimfarm`:

https://github.com/openzim/nautilus-webui/blob/bb80f61e2b4affac8bddecdd87f9b2744a911e53/backend/src/backend/database/__init__.py#L11-L35
`zimfarm` code: https://github.com/openzim/zimfarm/blob/4e9ea36542d90e8835e7e4323917e6ce4f4f2b3f/dispatcher/backend/src/db/__init__.py#L15-L36

This code includes a hack that use `bson` as the json serializer and deserializer. I guess the reasons that `zimfarm` used this hack is to keep the compatibility with the data from mongdb and I don't think we need to do this in `nautilus-webui` since we used PostgreSQL from scratch.

@rgaudin, @benoit74, Could you elaborate the reason why we used this hack in `zimfarm`?

**Comment by rgaudin** [comment]
I agree. If you can find one or implement the serializer/deserializer properly that works for JSON and postgres, that would be good.

**Comment by benoit74** [comment]
I think we could automate something like this:
- detect every new release of https://github.com/mongodb/mongo-python-driver
- for every release, extract the `bson` package and push it to a repo of our own
- release it under our own name

I checked that `bson` package has no dependency to other namespace in mongo driver, so it seems pretty straightforward.

Once this is automated, it would allow us to keep code / version numbering in sync and benefit from any bug fix / new feature / enhancement in the original codebase (which will continue to evolve since this is a central piece for Mongo).

We might even consider to release it under an organization distinct than kiwix so that others can contribute more easily + it would survive should Kiwix stop operations. I will try to contact people at https://github.com/py-bson to see what they think about this idea, it might be the good place.

**Comment by benoit74** [comment]
https://github.com/py-bson/bson/issues/124

**Comment by benoit74** [comment]
OK, I'm fine with this as well.

**Comment by FledgeXu** [comment]
Ok, Let's keep it for now.
