### ISSUE TITLE
ZIM file with limited number of PDFs engages in unlimited scrolling

### ISSUE THREAD

**Issue by Popolechien** [openzim/nautilus-webui#88]
Generated https://s3.us-west-1.wasabisys.com/org-kiwix-zimit/other/nautilus_f5881f68-940e-4c4a-a3d5-029424d4b0fa_b35e0d75f1da4d589689785284e915bd.zim with about 20 PDF files or so.

The resulting zim files works (ie I can read each PDF using either Kiwix-JS or Apple), but the ZIM I can scroll endlessly, which is a weird occurence (and particularly confusing since there is no order to the files, as mentioned in https://github.com/openzim/nautilus-webui/issues/85

**Comment by rgaudin** [comment]
Sorry my answer to #85 is partly incorrect. I was responding to the order in the collection but the display order in current nautilus is under the influence of random option (on by default, disabled with `--no-random`).
The infinite scroll is due to the fact that random is ON and pagination is lower than your number of entries. `--pagination` is set at `10` by default.

This is the normal behavior of nautilus.

The difference is that nautilus-webui doesn't allow you to change those options and thus uses the default values.

There are three ways out of this which can be complementary to each other over time:

- set better default for the webui (like `--no-random`, `--pagination 40`).
- allow setting some params. None were planned in the mockup. I added main-logo but there are others: `--no-random`, `--pagination`, `--show-description`, `--zim-file` (recorded but not passed to zimfarm),`--locale`, `--longdescription`, `--main-color`, `--secondary-color`, `--about`.
- wait for https://github.com/openzim/nautilus/issues/73 to be settled and implemented as all those options would be removed.

**Comment by rgaudin** [comment]
Turning this into a question and closing as there is nothing specific to do
